server:
  port: 8083
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ratingservice
    username: root
    password: ROOT
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

